name = "ifc-proplang-rocq"
language = "Rocq"
description = "Information Flow Control workload using the PropLang runner framework (Rocq/Coq)."
strategies = [
  "BespokeGenerator",
  "BespokeLLNIGenerator",
  "TypeBasedGenerator",
  "TypeBasedFuzzer",
  "VariationalGenerator",
  "VariationalMutatingGenerator",
]

mutations = [
  "OpLab_1",
  "OpMLab_1",
  "OpMLab_2",
  "OpPcLab_1",
  "OpBCall_1",
  "OpBCall_2",
  "OpBCall_3",
  "OpBCall_4",
  "OpBCall_5",
  "OpBCall_6",
  "OpBRet_1",
  "OpBRet_2",
  "OpBRet_3",
  "OpBRet_4",
  "OpBRet_5",
  "OpBRet_6",
  "OpBRet_7",
  "OpBRet_8",
  "OpBRet_9",
  "OpBRet_10",
  "OpBRet_11",
  "OpPutLab_1",
  "OpNop_1",
  "OpPut_1",
  "OpBinOp_1",
  "OpBinOp_2",
  "OpBinOp_3",
  "OpBinOp_4",
  "OpJump_1",
  "OpJump_2",
  "OpJump_3",
  "OpBNZ_1",
  "OpBNZ_2",
  "OpBNZ_3",
  "OpLoad_1",
  "OpLoad_2",
  "OpLoad_3",
  "OpLoad_4",
  "OpStore_1",
  "OpStore_2",
  "OpStore_3",
  "OpStore_4",
  "OpStore_5",
  "OpWrite_1",
  "OpWrite_2",
  "OpWrite_3",
  "OpWrite_4",
  "OpWrite_5",
  "OpWrite_6",
  "OpWrite_7",
  "OpWrite_8",
  "OpWrite_9",
  "OpWrite_10",
  "OpWrite_11",
  "OpAlloc_1",
  "OpAlloc_2",
  "OpAlloc_3",
  "OpAlloc_4",
  "OpPSetOff_1",
  "OpPSetOff_2",
  "OpPSetOff_3",
  "OpPSetOff_4",
  "OpPGetOff_1",
  "OpPGetOff_2",
  "OpMSize_1",
  "OpMSize_2",
  "OpMSize_3",
  "OpMSize_4",
  "OpMov_1",
  "OpMov_2",
]
